language: python
services:
  - redis-server
python:
  - "3.8"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script:
    - coverage run --source=formulae -m unittest discover
after_success:
    - coverage combine
    - coveralls
