"""add is_admin flag to users

Revision ID: 0c09c618645a
Revises: 8e1e2fd2031a
Create Date: 2026-05-05 15:10:32.917377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c09c618645a'
down_revision = '8e1e2fd2031a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_user_is_admin'),
            ['is_admin'],
            unique=False
        )

    op.execute("UPDATE user SET is_admin = 0 WHERE is_admin IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'is_admin',
            existing_type=sa.Boolean(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
