"""Added default locale

Revision ID: 49b9a36e244a
Revises: e5f584ece986
Create Date: 2018-06-28 10:27:32.669529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b9a36e244a'
down_revision = 'e5f584ece986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_locale', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_default_locale'), 'user', ['default_locale'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_default_locale'), table_name='user')
    op.drop_column('user', 'default_locale')
    # ### end Alembic commands ###
