 @startuml

    'actor "admin" as externaladmin 
    actor user


    interface "HTTP\nport 80\npublic" as 80
    interface "HTTPS\nport 443\npublic" as 443

frame akademie {
  component "elastic search" as elastic
}

frame uhhinternal{

    actor "admin" as internaladmin 
    'actor "user" as internaluser

frame vsphere { 
}
node tools { 
    component supervisor as supervisortools
    component gunicorn as gunicorntools
    component nginx as nginxtools
    component "formuale-capitains-nemo" as formulaetools
    'interface "HTTP\nport 8000\nprivate" as 8000tools
    portin "HTTP\nport 80\npublic" as internal80
    portin "HTTPS\nport 443\npublic" as internal443
    database corpora as corporatools
}

    'internaluser ..> internal80
    'internaluser ..> internal443
    'gunicorntools -0)- nginxtools: "HTTP\nport 8000\nprivate"
    nginxtools --> gunicorntools: "forward to"
    nginxtools -- internal443
    nginxtools -- internal80 

    supervisortools --> gunicorntools : controls
    'internaladmin --> supervisortools : manages

    'gunicorntools -- 8000tools
    'nginxtools ..> 8000tools : forwards to

    gunicorntools --> formulaetools : serves
    formulaetools --> corporatools: uses

}
    node werkstatt {
    component supervisor
    component varnish
    component gunicorn
    component nginx 
    component "formuale-capitains-nemo" as formulae
    interface "HTTP\nport 8000\nprivate" as 8000
    database corpora
    }
    
    formulae --> elastic: uses
    formulaetools --> elastic: uses
    
    
    nginx --> varnish: forward to 8080
    
    'internaladmin --> tools
    'internaladmin --> werkstatt
    'internaladmin --> vsphere
    
    vsphere --> werkstatt: controls
    vsphere --> tools: controls
    
    'formulae --> formulaetools: "beta version of"

    'server -- 80
    'server -- 443

    'user ..> 80 : use
    'user ..> 443 : use

    nginx -- 443
    nginx -- 80 

    supervisor --> gunicorn : controls
    'externaladmin --> supervisor : manages

    gunicorn -- 8000
    nginx ..> 8000 : forwards to

    gunicorn --> formulae : serves
    formulae --> corpora: uses

  @enduml