# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Formulae Werkstatt Testing

on:
  [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Docker Hub image that `build` executes in
    container: node:10.18-jessie
    
    # Service containers to run with `build`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 coveralls
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Code testing with coverage
      run: coverage run --source=formulae -m unittest discover
    - name: Post test results
      run: |
        coverage combine
        coveralls
